# -*- coding: utf-8 -*-
"""Easy_181. Employees Earning More Than Their Managers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XJtBmV7yNZkhet5EwTqn6Dl3km_wY86v
"""

'''

181. Employees Earning More Than Their Managers
Easy
2.2K
220
Companies
SQL Schema
Table: Employee

+-------------+---------+
| Column Name | Type    |
+-------------+---------+
| id          | int     |
| name        | varchar |
| salary      | int     |
| managerId   | int     |
+-------------+---------+
id is the primary key column for this table.
Each row of this table indicates the ID of an employee, their name, salary, and the ID of their manager.


Write an SQL query to find the employees who earn more than their managers.

Return the result table in any order.

The query result format is in the following example.



Example 1:

Input:
Employee table:
+----+-------+--------+-----------+
| id | name  | salary | managerId |
+----+-------+--------+-----------+
| 1  | Joe   | 70000  | 3         |
| 2  | Henry | 80000  | 4         |
| 3  | Sam   | 60000  | Null      |
| 4  | Max   | 90000  | Null      |
+----+-------+--------+-----------+
Output:
+----------+
| Employee |
+----------+
| Joe      |
+----------+
Explanation: Joe is the only employee who earns more than his manager.
'''

# Write your MySQL query statement below
Select e2.name as employee
FROM Employee as e1
INNER JOIN Employee e2 ON e1.id = e2.managerId
WHERE e1.salary < e2.salary

